"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100

format = """
$os\
$hostname\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
$nodejs\
$bun\
$rust\
$golang\
$php\
$cmd_duration\
$jobs\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$status$character"""

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = '[$symbol](bg:#a3aed2 fg:#090c0c)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#090c0c"
format = '[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
style = "bg:#a3aed2 fg:#090c0c"
format = '[[ $hostname ](bg:#a3aed2 fg:#090c0c)]($style)'

[status]
disabled = false
symbol = "✗"
success_symbol = ""
format = '[[ $symbol $status ](fg:#f7768e bg:#2a1a1a)]($style)'

[cmd_duration]
min_time = 2000
format = '[[ 󱎫 $duration ](fg:#e0af68 bg:#212736)]($style)'

[jobs]
symbol = "✦"
format = '[[ $symbol $number ](fg:#bb9af7 bg:#212736)]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[python]
symbol = "\ue73c"
style = "bg:#212736"
format = '[[ $symbol $virtualenv ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
